# Support Vector Machines in Python: SVM Concepts & Code
## Course by Start-Tech Academy on Udemy

### Numpy

In [3]:
import numpy as np

In [4]:
# initialize numpy array
# we can make our own array
np1 = np.array([1, 2, 3, 4])

In [5]:
np1

array([1, 2, 3, 4])

In [6]:
type(np1)

numpy.ndarray

In [7]:
# create a matrix
# basically matrices are lists containing other lists
mat1 = np.array([[1, 2], [3, 4]])

In [8]:
mat1

array([[1, 2],
       [3, 4]])

In [9]:
type(mat1) # it's still a numpy array

numpy.ndarray

In [14]:
# we can tell matrices dimension with shape function
np1.shape

(4,)

In [15]:
mat1.shape

(2, 2)

In [16]:
# we can only put one data type on numpy arrays
# we can check the data type with dtype function
mat1.dtype

dtype('int32')

In [17]:
# we can assign a value to the matrices by specifying it with equal operator
print("before:")
mat1

before:


array([[1, 2],
       [3, 4]])

In [19]:
mat1[0, 0] = 5 # assign the first data of the first list to 5
print("after:")
mat1

after:


array([[5, 2],
       [3, 4]])

In [21]:
# we use "range" to make a sequence in python lists
# we use "arange" to make a sequence in numpy lists
mat2 = np.arange(0, 10, 1)

In [22]:
mat2 # similar to python lists (first, last, step)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
mat3 = np.linspace(0, 10, 20)
# i guess "linspace" is linear space
# so we will generate an array starts with 0 and ends with 9
# with 20 values, divided linearly (?)

In [29]:
mat3
# "Return evenly spaced numbers over a specified interval."
# definition by the official documentation

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [34]:
mat4 = np.random.randint(2, size=(5, 5))
# random, yeah, self explanatory
# generates random values
# randint generates integers, 2 means 0 and 1
# if we change 2 to 5 it would generate values between 0 to 4
mat5 = np.random.randint(5, size=(5, 5))
# there are so many types of random, go to docs for more

In [37]:
print(mat4)
print(mat5)

[[1 0 0 0 1]
 [1 1 0 0 1]
 [1 0 0 1 0]
 [0 0 0 1 1]
 [0 0 0 0 0]]
[[0 1 3 1 1]
 [0 1 3 3 4]
 [3 0 0 2 1]
 [0 2 0 4 2]
 [1 1 2 2 1]]
